  name: Deploy to Github Pages
  on:
    push:
      branches:
        - main
  jobs:
    gh-pages-deploy:
      name: Deploying to Github Pages
      runs-on: ubuntu-latest
      steps:
          - uses: actions/checkout@v2
          - uses: actions/setup-node@v2
            with:
              node-version: '16'
          - name: Vue to Github Pages
            uses: xRealNeon/VuePagesAction@1.0.1
            with:
              username: "Thorben Below"
              reponame: "vue-firebase"
              gitemail: "deploy@ci.invalid"
              gitname: "ci"
              gitmsg: "deploy pages"
              token: ${{ secrets.GITHUB_TOKEN }}

