  name: Deploy to Github Pages
  on:
    push:
      branches:
        - main
  jobs:
    gh-pages-deploy:
      name: Deploying to Github Pages
      runs-on: ubuntu-latest
      environment: production
      env:
        VUE_APP_FIREBASE_API_KEY: ${{ secrets.VUE_APP_FIREBASE_API_KEY }}
        VUE_APP_FIREBASE_PROJECT_ID: ${{ secrets.VUE_APP_FIREBASE_PROJECT_ID }}
        CI_PROJECT_NAME: ${{ secrets.CI_PROJECT_NAME }}
      steps:
          - uses: actions/checkout@v2
          - uses: actions/setup-node@v2
            with:
              node-version: '16'
          - name: Vue to Github Pages
            uses: xRealNeon/VuePagesAction@1.0.1
            with:
              username: ${{ secrets.CI_GIT_USERNAME }}
              reponame: ${{ secrets.CI_PROJECT_NAME }}
              gitemail: "deploy@ci.invalid"
              gitname: "ci"
              gitmsg: "deploy pages"
              token: ${{ secrets.TOKEN }}

